# Generated by Django 3.0.5 on 2020-05-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_blog_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='img',
        ),
    ]
